"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { GlobalSearch } from "@/components/search/GlobalSearch";
import { useAuth } from "@/lib/auth/AuthProvider";
import { useNotes } from "@/lib/notes/NotesProvider";
import { useProjects } from "@/lib/projects/ProjectsProvider";
import { useLearning } from "@/lib/learning/LearningProvider";

const NAV = [{ href: "/", label: "Knowledge Map" }, { href: "/notes", label: "Notes" }, { href: "/learning", label: "Learning" }, { href: "/library", label: "ライブラリー" }];
export function AppHeader() {
  const pathname = usePathname(); const { status, user, signOut } = useAuth(); const { notes } = useNotes(); const { projects } = useProjects(); const { pages } = useLearning(); const [analysisOpen, setAnalysisOpen] = useState(false); const [projectsOpen, setProjectsOpen] = useState(false);
  const count = (href: string) => href === "/notes" ? notes.length : href === "/learning" ? pages.length : 0;
  const links = NAV.map((item) => { const active = item.href === "/" ? pathname === "/" : pathname.startsWith(item.href); return <Link key={item.href} href={item.href} aria-current={active ? "page" : undefined} className={`relative flex h-11 items-center whitespace-nowrap px-3 text-[13px] font-medium sm:h-14 ${active ? "text-[var(--color-ink)]" : "text-[var(--color-ink-muted)] hover:text-[var(--color-ink)]"}`}>{item.label}{count(item.href) > 0 && <span className="ml-1.5 text-[11px]">{count(item.href)}</span>}{active && <span className="absolute inset-x-3 bottom-0 h-[2px] bg-[var(--color-zenith)]" />}</Link>; });
  const analysis = <div className="relative" onMouseEnter={() => setAnalysisOpen(true)} onMouseLeave={() => setAnalysisOpen(false)}><button type="button" onClick={() => setAnalysisOpen((open) => !open)} onFocus={() => setAnalysisOpen(true)} aria-expanded={analysisOpen} className={`relative flex h-11 items-center whitespace-nowrap px-3 text-[13px] font-medium sm:h-14 ${pathname.startsWith("/frameworks") || pathname.startsWith("/web-marketing") ? "text-[var(--color-ink)]" : "text-[var(--color-ink-muted)] hover:text-[var(--color-ink)]"}`}>分析 <span className="ml-1 text-[10px]">▾</span>{(pathname.startsWith("/frameworks") || pathname.startsWith("/web-marketing")) && <span className="absolute inset-x-3 bottom-0 h-[2px] bg-[var(--color-zenith)]" />}</button>{analysisOpen && <div onFocus={() => setAnalysisOpen(true)} className="absolute left-0 top-full z-50 min-w-48 rounded-[5px] border border-[var(--color-line)] bg-white py-1 shadow-lg"><Link href="/frameworks" className="block px-3 py-2 text-[13px] hover:bg-[var(--color-surface-sunken)]">フレームワーク分析</Link><Link href="/web-marketing" className="block px-3 py-2 text-[13px] hover:bg-[var(--color-surface-sunken)]">ウェブマーケ分析</Link></div>}</div>;
  const projectMenu = <div className="relative" onMouseEnter={() => setProjectsOpen(true)} onMouseLeave={() => setProjectsOpen(false)}><button type="button" onClick={() => setProjectsOpen((open) => !open)} onFocus={() => setProjectsOpen(true)} aria-expanded={projectsOpen} className={`relative flex h-11 items-center whitespace-nowrap px-3 text-[13px] font-medium sm:h-14 ${pathname.startsWith("/projects") ? "text-[var(--color-ink)]" : "text-[var(--color-ink-muted)] hover:text-[var(--color-ink)]"}`}>プロジェクト <span className="ml-1.5 text-[11px]">{projects.length}</span> <span className="ml-1 text-[10px]">▾</span>{pathname.startsWith("/projects") && <span className="absolute inset-x-3 bottom-0 h-[2px] bg-[var(--color-zenith)]" />}</button>{projectsOpen && <div onFocus={() => setProjectsOpen(true)} className="absolute left-0 top-full z-50 max-h-80 min-w-56 overflow-y-auto rounded-[5px] border border-[var(--color-line)] bg-white py-1 shadow-lg"><Link href="/projects" className="block px-3 py-2 text-[13px] font-medium hover:bg-[var(--color-surface-sunken)]">プロジェクト一覧</Link>{projects.map((project) => <Link key={project.id} href={`/projects/${project.id}`} className="block truncate px-3 py-2 text-[13px] hover:bg-[var(--color-surface-sunken)]">{project.name || "無題のプロジェクト"}</Link>)}</div>}</div>;
  return <header className="sticky top-0 z-30 border-b border-[var(--color-line)] bg-white/92 backdrop-blur-[6px]"><div className="mx-auto flex h-14 w-full max-w-[1440px] items-center gap-3 px-4 sm:gap-4 sm:px-6 lg:px-8"><Link href="/" className="shrink-0 whitespace-nowrap text-[14px] font-bold">Business Knowledge<span className="ml-1.5 hidden font-normal text-[var(--color-ink-muted)] lg:inline">System</span></Link><nav aria-label="メイン" className="hidden items-center gap-1 sm:flex">{links.slice(0,1)}{projectMenu}{analysis}{links.slice(1)}</nav><div className="flex min-w-0 flex-1 items-center justify-end gap-2 sm:gap-3"><GlobalSearch />{status === "signed-in" && user ? <div className="flex items-center gap-2"><span className="hidden max-w-[18ch] truncate text-[12px] text-[var(--color-ink-muted)] lg:block">{user.email}</span><button type="button" onClick={() => void signOut()} className="h-9 rounded-[4px] border border-[var(--color-line)] px-2.5 text-[12px]">ログアウト</button></div> : <Link href="/login" className="h-9 rounded-[4px] border border-[var(--color-line)] px-3 text-[12px] leading-9">ログイン</Link>}</div></div><nav aria-label="メイン（狭い画面）" className="scroll-area flex items-center gap-1 overflow-x-auto border-t border-[var(--color-line-faint)] px-2 sm:hidden">{links.slice(0,1)}{projectMenu}{analysis}{links.slice(1)}</nav></header>;
}