"use client";
import { useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/auth/AuthProvider";
import { useProjects } from "@/lib/projects/ProjectsProvider";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import { normalizeWebMarketingResult } from "@/lib/web-marketing/schemas";
import type { WebMarketingAnalysisRow } from "@/lib/supabase/types";

export function WebMarketingWorkspace() {
  const { user } = useAuth(); const { projects } = useProjects(); const supabase = useMemo(() => getSupabaseBrowserClient(), []);
  const [rows, setRows] = useState<WebMarketingAnalysisRow[]>([]); const [url, setUrl] = useState(""); const [notes, setNotes] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [selected, setSelected] = useState<WebMarketingAnalysisRow | null>(null);
  useEffect(() => { if (!supabase || !user) return; void supabase.from("web_marketing_analyses").select("*").order("generated_at", { ascending: false }).then(({ data }) => { const next = data ?? []; setRows(next); setSelected(next[0] ?? null); }); }, [supabase, user]);
  const generate = async () => { setBusy(true); setError(null); try { const response = await fetch("/api/web-marketing/analyze", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ sourceUrl: url, notes }) }); const payload = await response.json(); if (!response.ok || !payload.result) throw new Error(payload.error?.message); if (!supabase || !user) throw new Error("ログインが必要です。"); const { data, error: saveError } = await supabase.from("web_marketing_analyses").insert({ user_id: user.id, source_url: payload.source.url, source_notes: notes, source_metadata: payload.source, result_data: payload.result, model: payload.model, source_fetched_at: payload.source.fetchedAt }).select().single(); if (saveError || !data) throw new Error(saveError?.message); setRows((current) => [data, ...current]); setSelected(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "生成に失敗しました。"); } finally { setBusy(false); } };
  const result = selected ? normalizeWebMarketingResult(selected.result_data) : null;
  return <div className="scroll-area min-h-0 flex-1 overflow-y-auto bg-white"><div className="mx-auto grid max-w-[1180px] gap-8 px-5 py-6 lg:grid-cols-[260px_1fr]"><aside><h1 className="text-[20px] font-bold">ウェブマーケ分析</h1><p className="mt-2 text-[13px] text-[var(--color-ink-muted)]">URLを根拠に、サイトの課題と打ち手を整理します。</p><div className="mt-5 space-y-1">{rows.map((row) => <button key={row.id} onClick={() => setSelected(row)} className="block w-full rounded px-3 py-2 text-left text-[13px] hover:bg-[var(--color-surface-sunken)]">{row.source_url}</button>)}</div></aside><main><section className="border-b pb-6"><h2 className="text-[16px] font-semibold">新しいサイト分析</h2><input className="field mt-4" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://example.com" /><textarea className="field mt-3 min-h-24 py-2" value={notes} onChange={(e) => setNotes(e.target.value)} placeholder="事業目標・確認したい顧客・競合など（任意）" /><button disabled={busy} onClick={() => void generate()} className="mt-3 h-10 rounded bg-[var(--color-zenith)] px-4 text-[13px] text-white disabled:opacity-50">{busy ? "分析中…" : "ウェブマーケ分析を生成"}</button>{error && <p className="mt-2 text-[13px] text-[var(--color-danger)]">{error}</p>}</section>{result && <article className="mt-7"><h2 className="text-[22px] font-bold">{result.title}</h2><p className="mt-3 leading-7 text-[var(--color-ink-secondary)]">{result.executiveSummary}</p><Section title="現状" items={result.currentState}/><section className="mt-6"><h3 className="font-semibold">優先課題</h3>{result.issues.map((issue) => <div key={issue.title} className="mt-3 rounded border p-3"><b>{issue.title}</b><p className="mt-1 text-[13px]">根拠：{issue.evidence}</p><p className="mt-1 text-[13px]">影響：{issue.impact}</p></div>)}</section><Section title="戦略的示唆" items={result.insights}/><Section title="優先打ち手" items={result.priorityActions.map((action) => `${action.action}（成功指標：${action.successSignal}）`)}/><Section title="KPI" items={result.kpis}/><Section title="追加確認事項" items={result.openQuestions}/><section className="mt-8 border-t pt-4"><h3 className="font-semibold">プロジェクトに追加</h3>{projects.map((project) => <label key={project.id} className="mt-2 flex items-center gap-2 text-[13px]"><input type="checkbox" onChange={async (event) => { if (!supabase || !selected) return; if (event.target.checked) await supabase.from("web_marketing_analysis_projects").upsert({ web_marketing_analysis_id: selected.id, project_id: project.id }); else await supabase.from("web_marketing_analysis_projects").delete().eq("web_marketing_analysis_id", selected.id).eq("project_id", project.id); }} />{project.name}</label>)}</section></article>}</main></div></div>;
}
function Section({ title, items }: { title: string; items: string[] }) { return <section className="mt-6"><h3 className="font-semibold">{title}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-[13px] leading-6">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
